### ISSUE TITLE
License

### ISSUE THREAD

**Issue by frenzymadness** [bholley/atomic_refcell#17]
Hello.

Would it be possible to add a license file to this repo, please?

**Comment by bholley** [comment]
Done.

**Comment by anp** [comment]
Hi! I'm reviewing this crate for use in Fuchsia, and it looks like the [license](https://github.com/bholley/atomic_refcell/blob/master/LICENSE.APACHE) [files](https://github.com/bholley/atomic_refcell/blob/master/LICENSE.MIT) that were added to the repo don't match the [license header in lib.rs](https://github.com/bholley/atomic_refcell/blob/3ae6dab4efb06bc64f00ac25356ffce8cb9b59ad/src/lib.rs#L1-L3). Would it be possible to update the license headers to match the license files? IANAL but that might be a relicensing that requires contributors to approve.

**Comment by bholley** [comment]
That MPL license header was an oversight on my part, and I've just pushed a patch to remove it. Cargo.toml has specified the license as Apache2/MIT since inception (which is displayed prominently on crates.io).

Also not a lawyer, but I think you could make the argument that contributions to date have effectively been tri-licensed and/or that any contributor who cared about the distinction between Apache2/MIT and MPL would have been responsible for flagging the inconsistency.

**Comment by anp** [comment]
Awesome, thanks! Your reasoning makes sense to me, any chance you'd be able to publish an updated patch version to crates.io with that change?

**Comment by bholley** [comment]
Done.

**Comment by anp** [comment]
Wonderful, thank you!
