### ISSUE TITLE
Improve mapping features

### ISSUE THREAD

**Issue by gzp79** [bholley/atomic_refcell#19]
There's an already open request about an owned_map feature that return a non-borrowed object.
Please consider improving the API with other construct as well:
- map : `&T -> &(mut) U`
- filter_map : `&T -> Option<&(mut) U>`
- try_map : `&T -> Result<&(mut) U, E>`
- and their "owning" version as described in #11 

I felt like this is a bit broader request as the #11, thus I've created a new issue.

**Comment by ten3roberts** [comment]
I'd absolutely love this.

What I think would be great is a `&mut (T, U) -> (&mut T, &mut U)` because it is quite common to have a single refcell to lock multiple pieces of data, but you'd need to return them as disjoint references. Two atomic refcells does partly solve the issue, but required double borrowing each time
